/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const ActivityIndexView: typeof import('./views/activity-index-view').ActivityIndexView
  const ActivityListTable: typeof import('./components/activity-list-table').ActivityListTable
  const Alert: typeof import('./components/ui/alert').Alert
  const AlertAction: typeof import('./components/ui/alert').AlertAction
  const AlertDescription: typeof import('./components/ui/alert').AlertDescription
  const AlertDialog: typeof import('./components/ui/alert-dialog').AlertDialog
  const AlertDialogAction: typeof import('./components/ui/alert-dialog').AlertDialogAction
  const AlertDialogCancel: typeof import('./components/ui/alert-dialog').AlertDialogCancel
  const AlertDialogContent: typeof import('./components/ui/alert-dialog').AlertDialogContent
  const AlertDialogDescription: typeof import('./components/ui/alert-dialog').AlertDialogDescription
  const AlertDialogFooter: typeof import('./components/ui/alert-dialog').AlertDialogFooter
  const AlertDialogHeader: typeof import('./components/ui/alert-dialog').AlertDialogHeader
  const AlertDialogMedia: typeof import('./components/ui/alert-dialog').AlertDialogMedia
  const AlertDialogOverlay: typeof import('./components/ui/alert-dialog').AlertDialogOverlay
  const AlertDialogPortal: typeof import('./components/ui/alert-dialog').AlertDialogPortal
  const AlertDialogTitle: typeof import('./components/ui/alert-dialog').AlertDialogTitle
  const AlertDialogTrigger: typeof import('./components/ui/alert-dialog').AlertDialogTrigger
  const AlertTitle: typeof import('./components/ui/alert').AlertTitle
  const AppSidebar: typeof import('./components/app-sidebar').AppSidebar
  const AssetCreateForm: typeof import('./components/asset-create-form').AssetCreateForm
  const AssetCreateView: typeof import('./views/asset-create-view').AssetCreateView
  const AssetDetailView: typeof import('./views/asset-detail-view').AssetDetailView
  const AssetEditForm: typeof import('./components/asset-edit-form').AssetEditForm
  const AssetEditView: typeof import('./views/asset-edit-view').AssetEditView
  const AssetIndexView: typeof import('./views/asset-index-view').AssetIndexView
  const AssetListTable: typeof import('./components/asset-list-table').AssetListTable
  const AuthLayout: typeof import('./layouts/auth-layout').AuthLayout
  const Avatar: typeof import('./components/ui/avatar').Avatar
  const AvatarBadge: typeof import('./components/ui/avatar').AvatarBadge
  const AvatarFallback: typeof import('./components/ui/avatar').AvatarFallback
  const AvatarGroup: typeof import('./components/ui/avatar').AvatarGroup
  const AvatarGroupCount: typeof import('./components/ui/avatar').AvatarGroupCount
  const AvatarImage: typeof import('./components/ui/avatar').AvatarImage
  const BackButton: typeof import('./components/back-button').BackButton
  const Badge: typeof import('./components/ui/badge').Badge
  const BaselineBadge: typeof import('./views/asset-detail-view').BaselineBadge
  const Button: typeof import('./components/ui/button').Button
  const Card: typeof import('./components/ui/card').Card
  const CardAction: typeof import('./components/ui/card').CardAction
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const CategoryBadge: typeof import('./components/activity-list-table').CategoryBadge
  const Char: typeof import("./components/char-area-gradient").Char
  const ChartAreaGradient: typeof import("./components/char-area-gradient").ChartAreaGradient
  const ChartAreaInteractive: typeof import('./components/chart-area-interactive').ChartAreaInteractive
  const ChartContainer: typeof import('./components/ui/chart').ChartContainer
  const ChartLegend: typeof import('./components/ui/chart').ChartLegend
  const ChartLegendContent: typeof import('./components/ui/chart').ChartLegendContent
  const ChartStyle: typeof import('./components/ui/chart').ChartStyle
  const ChartTooltip: typeof import('./components/ui/chart').ChartTooltip
  const ChartTooltipContent: typeof import('./components/ui/chart').ChartTooltipContent
  const Checkbox: typeof import('./components/ui/checkbox').Checkbox
  const ComplianceStatusBadge: typeof import("./views/asset-detail-view").ComplianceStatusBadge
  const ConditionBadge: typeof import('./components/asset-list-table').ConditionBadge
  const Controller: typeof import('react-hook-form').Controller
  const DashboardCards: typeof import('./components/dashboard-cards').DashboardCards
  const DashboardCardsItem: typeof import("./components/dashboard-cards").DashboardCardsItem
  const DashboardChart: typeof import('./components/dashboard-chart').DashboardChart
  const DashboardEosWarning: typeof import('./components/dashboard-eos-warning').DashboardEosWarning
  const DashboardTable: typeof import('./components/ui/dashboard-table').DashboardTable
  const DashboardView: typeof import('./views/dashboard-view').DashboardView
  const DropdownMenu: typeof import('./components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuTrigger
  const EosWarningAlert: typeof import('./components/eos-warning-alert').EosWarningAlert
  const Field: typeof import('./components/ui/field').Field
  const FieldContent: typeof import('./components/ui/field').FieldContent
  const FieldDescription: typeof import('./components/ui/field').FieldDescription
  const FieldError: typeof import('./components/ui/field').FieldError
  const FieldGroup: typeof import('./components/ui/field').FieldGroup
  const FieldInput: typeof import('./components/field-input').FieldInput
  const FieldInputSelect: typeof import('./components/field-input').FieldInputSelect
  const FieldLabel: typeof import('./components/ui/field').FieldLabel
  const FieldLegend: typeof import('./components/ui/field').FieldLegend
  const FieldSeparator: typeof import('./components/ui/field').FieldSeparator
  const FieldSet: typeof import('./components/ui/field').FieldSet
  const FieldTitle: typeof import('./components/ui/field').FieldTitle
  const Fragment: typeof import('react').Fragment
  const Input: typeof import('./components/ui/input').Input
  const Label: typeof import('./components/ui/label').Label
  const Link: typeof import('react-router').Link
  const LoginForm: typeof import('./components/login-form').LoginForm
  const LoginView: typeof import('./views/login-view').LoginView
  const MainLayout: typeof import('./layouts/main-layout').MainLayout
  const MaintenanceDialog: typeof import('./components/maintenance-dialog').MaintenanceDialog
  const MutasiDialog: typeof import('./components/mutasi-dialog').MutasiDialog
  const NotFoundView: typeof import('./views/not-found-view').NotFoundView
  const OfficeCreateForm: typeof import('./components/office-create-form').OfficeCreateForm
  const OfficeCreateView: typeof import('./views/office-create-view').OfficeCreateView
  const OfficeDetailView: typeof import('./views/office-detail-view').OfficeDetailView
  const OfficeEditForm: typeof import('./components/office-edit-form').OfficeEditForm
  const OfficeEditView: typeof import('./views/office-edit-view').OfficeEditView
  const OfficeIndexView: typeof import('./views/office-index-view').OfficeIndexView
  const OfficeListTable: typeof import('./components/office-list-table').OfficeListTable
  const OfficeListView: typeof import("./views/office-index-view").OfficeListView
  const Outlet: typeof import('react-router').Outlet
  const PageHeader: typeof import('./components/page-header').PageHeader
  const RoomCreateForm: typeof import('./components/room-create-form').RoomCreateForm
  const RoomCreateView: typeof import('./views/room-create-view').RoomCreateView
  const RoomEditForm: typeof import('./components/room-edit-form').RoomEditForm
  const RoomEditView: typeof import('./views/room-edit-view').RoomEditView
  const RoomSelectField: typeof import('./components/room-select-field').RoomSelectField
  const Select: typeof import('./components/ui/select').Select
  const SelectContent: typeof import('./components/ui/select').SelectContent
  const SelectGroup: typeof import('./components/ui/select').SelectGroup
  const SelectGroupLabel: typeof import("./components/ui/select").SelectGroupLabel
  const SelectItem: typeof import('./components/ui/select').SelectItem
  const SelectLabel: typeof import('./components/ui/select').SelectLabel
  const SelectScrollDownButton: typeof import('./components/ui/select').SelectScrollDownButton
  const SelectScrollUpButton: typeof import('./components/ui/select').SelectScrollUpButton
  const SelectSeparator: typeof import('./components/ui/select').SelectSeparator
  const SelectTrigger: typeof import('./components/ui/select').SelectTrigger
  const SelectValue: typeof import('./components/ui/select').SelectValue
  const Separator: typeof import('./components/ui/separator').Separator
  const Sheet: typeof import('./components/ui/sheet').Sheet
  const SheetClose: typeof import('./components/ui/sheet').SheetClose
  const SheetContent: typeof import('./components/ui/sheet').SheetContent
  const SheetDescription: typeof import('./components/ui/sheet').SheetDescription
  const SheetFooter: typeof import('./components/ui/sheet').SheetFooter
  const SheetHeader: typeof import('./components/ui/sheet').SheetHeader
  const SheetTitle: typeof import('./components/ui/sheet').SheetTitle
  const SheetTrigger: typeof import('./components/ui/sheet').SheetTrigger
  const Sidebar: typeof import('./components/ui/sidebar').Sidebar
  const SidebarContent: typeof import('./components/ui/sidebar').SidebarContent
  const SidebarFooter: typeof import('./components/ui/sidebar').SidebarFooter
  const SidebarGroup: typeof import('./components/ui/sidebar').SidebarGroup
  const SidebarGroupAction: typeof import('./components/ui/sidebar').SidebarGroupAction
  const SidebarGroupContent: typeof import('./components/ui/sidebar').SidebarGroupContent
  const SidebarGroupLabel: typeof import('./components/ui/sidebar').SidebarGroupLabel
  const SidebarHeader: typeof import('./components/ui/sidebar').SidebarHeader
  const SidebarInput: typeof import('./components/ui/sidebar').SidebarInput
  const SidebarInset: typeof import('./components/ui/sidebar').SidebarInset
  const SidebarMenu: typeof import('./components/ui/sidebar').SidebarMenu
  const SidebarMenuAction: typeof import('./components/ui/sidebar').SidebarMenuAction
  const SidebarMenuBadge: typeof import('./components/ui/sidebar').SidebarMenuBadge
  const SidebarMenuButton: typeof import('./components/ui/sidebar').SidebarMenuButton
  const SidebarMenuItem: typeof import('./components/ui/sidebar').SidebarMenuItem
  const SidebarMenuSkeleton: typeof import('./components/ui/sidebar').SidebarMenuSkeleton
  const SidebarMenuSub: typeof import('./components/ui/sidebar').SidebarMenuSub
  const SidebarMenuSubButton: typeof import('./components/ui/sidebar').SidebarMenuSubButton
  const SidebarMenuSubItem: typeof import('./components/ui/sidebar').SidebarMenuSubItem
  const SidebarProvider: typeof import('./components/ui/sidebar').SidebarProvider
  const SidebarRail: typeof import('./components/ui/sidebar').SidebarRail
  const SidebarSeparator: typeof import('./components/ui/sidebar').SidebarSeparator
  const SidebarTrigger: typeof import('./components/ui/sidebar').SidebarTrigger
  const Skeleton: typeof import('./components/ui/skeleton').Skeleton
  const Suspense: typeof import('react').Suspense
  const Table: typeof import('./components/ui/table').Table
  const TableBody: typeof import('./components/ui/table').TableBody
  const TableCell: typeof import('./components/ui/table').TableCell
  const TableHead: typeof import('./components/ui/table').TableHead
  const TableHeader: typeof import('./components/ui/table').TableHeader
  const TableRow: typeof import('./components/ui/table').TableRow
  const Toaster: typeof import('./components/ui/sonner').Toaster
  const Tooltip: typeof import('./components/ui/tooltip').Tooltip
  const TooltipContent: typeof import('./components/ui/tooltip').TooltipContent
  const TooltipProvider: typeof import('./components/ui/tooltip').TooltipProvider
  const TooltipTrigger: typeof import('./components/ui/tooltip').TooltipTrigger
  const ValidationError: typeof import('./lib/errors').ValidationError
  const activityPropertiesLabel: typeof import('./schemas/activity-schema').activityPropertiesLabel
  const badgeVariants: typeof import('./components/ui/badge').badgeVariants
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./lib/utils').cn
  const columns: typeof import("./components/data-table-demo").columns
  const createAssetFormSchema: typeof import('./schemas/asset-schema').createAssetFormSchema
  const createContext: typeof import('react').createContext
  const createOfficeFormSchema: typeof import('./schemas/office-schema').createOfficeFormSchema
  const createRef: typeof import('react').createRef
  const createRoomFormSchema: typeof import('./schemas/room-schema').createRoomFormSchema
  const cva: typeof import('class-variance-authority').cva
  const description: typeof import('./components/chart-area-interactive').description
  const forwardRef: typeof import('react').forwardRef
  const http: typeof import('./lib/http').http
  const isHttpError: typeof import('./lib/http').isHttpError
  const isValidationError: typeof import('./lib/errors').isValidationError
  const lazy: typeof import('react').lazy
  const loginFormSchema: typeof import('./schemas/login-schema').loginFormSchema
  const memo: typeof import('react').memo
  const setFormErrors: typeof import('./lib/forms').setFormErrors
  const startTransition: typeof import('react').startTransition
  const toDatetimeText: typeof import('./lib/utils').toDatetimeText
  const toast: typeof import('sonner').toast
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useActivities: typeof import('./hooks/use-activity').useActivities
  const useAsset: typeof import('./hooks/use-asset').useAsset
  const useAssetActivities: typeof import('./hooks/use-activity').useAssetActivities
  const useAssetDetail: typeof import('./hooks/use-asset').useAssetDetail
  const useAuth: typeof import('./hooks/use-auth').useAuth
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useForm: typeof import('react-hook-form').useForm
  const useHref: typeof import('react-router').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useIsMobile: typeof import('./hooks/use-mobile').useIsMobile
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router').useNavigate
  const useNavigationType: typeof import('react-router').useNavigationType
  const useOffice: typeof import('./hooks/use-office').useOffice
  const useOfficeDetail: typeof import('./hooks/use-office').useOfficeDetail
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router').useOutlet
  const useOutletContext: typeof import('react-router').useOutletContext
  const useParams: typeof import('react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router').useResolvedPath
  const useRoutes: typeof import('react-router').useRoutes
  const useSWR: typeof import('swr').default
  const useSWRConfig: typeof import('swr').useSWRConfig
  const useSidebar: typeof import('./components/ui/sidebar').useSidebar
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const z: typeof import('./lib/utils').z
  const zodResolver: typeof import('@hookform/resolvers/zod').zodResolver
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ComponentProps } from 'react'
  import('react')
  // @ts-ignore
  export type { VariantProps } from 'class-variance-authority'
  import('class-variance-authority')
  // @ts-ignore
  export type { ChartConfig } from './components/ui/chart'
  import('./components/ui/chart')
  // @ts-ignore
  export type { HttpResponse } from './lib/http'
  import('./lib/http')
  // @ts-ignore
  export type { ZInfer } from './lib/utils'
  import('./lib/utils')
  // @ts-ignore
  export type { CreateAssetFormInput } from './schemas/asset-schema'
  import('./schemas/asset-schema')
  // @ts-ignore
  export type { LoginInput, LoginSuccess, LoginValidationError, LoginResponse } from './schemas/login-schema'
  import('./schemas/login-schema')
  // @ts-ignore
  export type { CreateOfficeInput } from './schemas/office-schema'
  import('./schemas/office-schema')
  // @ts-ignore
  export type { CreateRoomInput } from './schemas/room-schema'
  import('./schemas/room-schema')
}
