/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AuthLayout: typeof import('./layouts/auth-layout').AuthLayout
  const Button: typeof import('./components/ui/button').Button
  const Card: typeof import('./components/ui/card').Card
  const CardAction: typeof import('./components/ui/card').CardAction
  const CardContent: typeof import('./components/ui/card').CardContent
  const CardDescription: typeof import('./components/ui/card').CardDescription
  const CardFooter: typeof import('./components/ui/card').CardFooter
  const CardHeader: typeof import('./components/ui/card').CardHeader
  const CardTitle: typeof import('./components/ui/card').CardTitle
  const Checkbox: typeof import('./components/ui/checkbox').Checkbox
  const Controller: typeof import('react-hook-form').Controller
  const Field: typeof import('./components/ui/field').Field
  const FieldContent: typeof import('./components/ui/field').FieldContent
  const FieldDescription: typeof import('./components/ui/field').FieldDescription
  const FieldError: typeof import('./components/ui/field').FieldError
  const FieldGroup: typeof import('./components/ui/field').FieldGroup
  const FieldLabel: typeof import('./components/ui/field').FieldLabel
  const FieldLegend: typeof import('./components/ui/field').FieldLegend
  const FieldSeparator: typeof import('./components/ui/field').FieldSeparator
  const FieldSet: typeof import('./components/ui/field').FieldSet
  const FieldTitle: typeof import('./components/ui/field').FieldTitle
  const Fragment: typeof import('react').Fragment
  const Input: typeof import('./components/ui/input').Input
  const Label: typeof import('./components/ui/label').Label
  const LoginForm: typeof import('./components/login-form').LoginForm
  const LoginView: typeof import('./views/login-view').LoginView
  const Separator: typeof import('./components/ui/separator').Separator
  const Suspense: typeof import('react').Suspense
  const ValidationError: typeof import('./lib/errors').ValidationError
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./lib/utils').cn
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const http: typeof import('./lib/http').http
  const isHttpError: typeof import('./lib/http').isHttpError
  const isValidationError: typeof import('./lib/errors').isValidationError
  const lazy: typeof import('react').lazy
  const loginFormSchema: typeof import('./schemas/login-schema').loginFormSchema
  const memo: typeof import('react').memo
  const setFormErrors: typeof import('./lib/forms').setFormErrors
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAuth: typeof import('./hooks/use-auth').useAuth
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useForm: typeof import('react-hook-form').useForm
  const useHref: typeof import('react-router').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router').useNavigate
  const useNavigationType: typeof import('react-router').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router').useOutlet
  const useOutletContext: typeof import('react-router').useOutletContext
  const useParams: typeof import('react-router').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router').useResolvedPath
  const useRoutes: typeof import('react-router').useRoutes
  const useSWR: typeof import('swr').default
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const z: typeof import('./lib/utils').z
  const zodResolver: typeof import('@hookform/resolvers/zod').zodResolver
}
// for type re-export
declare global {
  // @ts-ignore
  export type { HttpResponse } from './lib/http'
  import('./lib/http')
  // @ts-ignore
  export type { ZInfer } from './lib/utils'
  import('./lib/utils')
  // @ts-ignore
  export type { LoginInput, LoginSuccess, LoginValidationError, LoginResponse } from './schemas/login-schema'
  import('./schemas/login-schema')
}
